Update nodeci.yml

diff --git a/.github/workflows/nodeci.yml b/.github/workflows/nodeci.yml
--- a/.github/workflows/nodeci.yml
+++ b/.github/workflows/nodeci.yml
@@ -67,11 +67,6 @@ jobs:
     - name: Build Docker Image
       run: docker build -t shivang1012/node-hello .
 
-    - name: Save Docker image as artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: shivang1012/node-hello
-        path: .  # You may need to adjust this path
 
     - name: Run Docker container
       run: docker run -d --name my-node-app  shivang1012/node-hello 
@@ -87,25 +82,19 @@ jobs:
             exit 1
           fi
 
-  next_job:
-    needs: build
-    runs-on: ubuntu-latest
-
-    steps:
-
-    - name: Checkout repository
-      uses: actions/checkout@v2
-
-    - name: Download Docker image artifact
-      uses: actions/download-artifact@v2
-      with:
-       name: shivang1012/node-hello 
-       path: .  # You may need to adjust this path
-
-    - name: Load Docker image
-      run: docker load -i shivang1012/node-hello .tar
+    # - name: Health Check
+    #   if: success()  # Proceed if previous steps succeededff
+    #   run: |
+    #       response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:7050/health-check)
+    #       if [ "$response" -ne 200 ]; then
+    #         echo "Health check failed with status $response"
+    #         exit 1
+    #       fi
+    #       echo "Health check passed with status $response"
+    
  
     - name: Login to Docker Hub
+      if: success()
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
